version: '3'
services:  
# ---------- Hadoop-Docker ----------
    hadoop:
        image: 'marcelmittelstaedt/spark_base:latest'
        container_name: hadoop
        build:
          context: ./hadoop
          dockerfile: Dockerfile        
        ports:
            - '8030:8030'
            - '8031:8031'
            - '9000:9000'
            - '8888:8888'
            - '8088:8088'
            - '9870:9870'
            - '9864:9864'
            - '10000:10000'
            - '8032:8032'
        restart: 'always'
# ---------- MariaDB-Docker ----------
    mariadb:
      image: 'mariadb:latest'
      container_name: mariaDB
      build:
        context: ./mariaDB
        dockerfile: Dockerfile
      environment:
        - MARIADB_ROOT_PASSWORD=root
        - MARIADB_DATABASE=ocid_cell_tower
      ports:
        - "3306:3306"
      restart: 'always'
# ---------- UI-Docker ---------- 
    UI:
      image: node:16
      container_name: UI
      build:
        context: ./UserInterface
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      restart: always
# ---------- Airflow-Docker ----------
    airflow:
        image: 'marcelmittelstaedt/airflow:latest'
        container_name: airflow
        build:
          context: ./airflow
          dockerfile: Dockerfile
        ports:
            - '8080:8080'
        restart: 'always'